### ISSUE TITLE
Control the whole Interface

### ISSUE THREAD

**Issue by antonkluev** [DavidLGoldberg/jumpy#90] opened 2016-08-30 16:52 UTC
feature request to control the whole Atom with jumps?

**Comment by DavidLGoldberg** [comment] 2016-08-30 17:02
Interested in adding more functionality, for instance tabs, etc.
duplicate of https://github.com/DavidLGoldberg/jumpy/issues/70

**Closed by DavidLGoldberg** 2016-08-30 17:02 UTC
