### ISSUE TITLE
Jumpy doesn't work after upgrade to Atom 1.3.3

### ISSUE THREAD

**Issue by klemensschindler** [DavidLGoldberg/jumpy#83] opened 2016-01-09 22:52 UTC
# Steps to reproduce
1. Attempt to open jumpy in Atom 1.3.3 by pressing Shift+Enter

# Extra info
**Atom Version**: 1.3.3
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [jumpy](https://github.com/DavidLGoldberg/jumpy) package, v2.0.10

### Stack Trace

Uncaught TypeError: Cannot read property '0' of null

```
At /C:/Users/user/.atom/packages/jumpy/lib/jumpy-view.coffee:290

TypeError: Cannot read property '0' of null
    at file:///C:/Users/user/.atom/packages/jumpy/lib/jumpy-view.coffee:192:14
    at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\src\workspace.js:282:9)
    at JumpyView.module.exports.JumpyView.toggle (file:///C:/Users/user/.atom/packages/jumpy/lib/jumpy-view.coffee:158:41)
    at atom-workspace.commands.add.atom.commands.add.jumpy:toggle (file:///C:/Users/user/.atom/packages/jumpy/lib/jumpy-view.coffee:44:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.3.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:10.7.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:39.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 jumpy:toggle (atom-text-editor.editor)
     -0:00.4.0 jumpy:f (atom-text-editor.editor.jumpy-jump-mode.is-focused)
     -0:00.4.0 jumpy:d (atom-text-editor.editor.jumpy-jump-mode.is-focused)
     -0:00.4.0 jumpy:s (atom-text-editor.editor.jumpy-jump-mode.is-focused)
     -0:00.2.0 jumpy:clear (atom-text-editor.editor.jumpy-jump-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
jumpy, v2.0.10
language-plantuml, v0.2.0
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
save-session, v0.16.0

# Dev
No dev packages
```

**Comment by DavidLGoldberg** [comment] 2016-01-12 06:06
Hi, I missed this this weekend sorry about that.  I've started a new branch for a version that is mostly fine in 1.3.3.  I've been using it since 1.3.2 to improve the performance, but the problem is there's some big bugs with labels jumping panes etc.  I'm trying to work through some code to be able to release the new version.  If someone sees a quick fix for this (keeping old lousy performance) I'd take a pull request.  I have limited time and want to truck forward.

**Comment by DavidLGoldberg** [comment] 2016-01-12 06:07
I haven't even confirmed the above, due to another issue where my jumpy version wasn't rolled back when I unpublished (it's a core issue somewhere)

**Comment by pvorona** [comment] 2016-02-11 18:13
This issue is easy to reproduce:
1. Open 2 tabs
2. tumpy:toggle in first pane
3. DONT press any jumpy keys, press ESC instead
4. Go to another tab, jumpy:toggle
and u get an error.
Also, i'm wondering what is the current state of performance optimization?

**Comment by DavidLGoldberg** [comment] 2016-02-12 01:21
I've been very busy.

@pvorona The branch is:
use_markers_and_decorations
https://github.com/DavidLGoldberg/jumpy/tree/use_markers_and_decorations
I see you have some experience with Atom package dev.
I'm off from work on Monday, and should be able to work on this would you want to do a google hangout and pair on it?  Last I left off, I was a little stuck. (My gmail is my github if you want to add me and try to collab / pair on this)

The issue with the above branch is that the decorations jump out of the panes.  I've seen other issues reported with this kind of problem....Thought it was a little premature to go live ignoring this.

(Confusing warning below):
The recreating of the issue wasn't so easy for me because there's a bug in core (open issue somewhere last I checked) that like thinks my jumpy is on a higher version (even though i rolled it back presumably worked for most others) 

I could / would have checked out an old sha to see if the main line branch is broke for real, but I thought it was working as this original issue I think was made from a few users who happened to upgrade (I thought) during the wrong time.  I'll try to take a look at this all ASAP.

**Comment by DavidLGoldberg** [comment] 2016-02-13 18:09
Got further, should have a release on Monday.

**Comment by DavidLGoldberg** [comment] 2016-02-15 23:33
Launched.  New version 3.0.1

**Closed by DavidLGoldberg** 2016-02-15 23:33 UTC
Labels: bug, help wanted
